#include "olus2000.h"

HELLO I AM OLUS2000 AND I WROTE THIS ENTRY. SO MAKE YOUR GUESSES WITH THAT IN MIND.
YOU DON/*'*/T BELIEVE ME? BUT WHY? HAVE I LIED TO YOU BEFORE? PLEASE,
JUST DRAG MY NICK TO THE APPROPRIATE PLACE. YOU WOULDN/*'*/T WANT TO SEE ME SAD WOULD YOU?
YOU STILL DONT BELIEVE ME? FINE... MY FULL NAME IS ALEKSANDER SABAK. I STUDIED
COMPUTER SCIENCE IN WARSAW UNIVERSITY OF TECHNOLOGY. I LOVE PICO8, ESOLANGS, AND
CONCATANATIVE PROGRAMMING. UMM... OH YEAH AND ALSO TOKI PONA. UHH...
IM FROM POLAND. YOU PROBABLY KNOW IT ALREADY, I JUST WANTED TO POINT IT OUT...
YOU NOW BELIEVE ME, RIGHT? :PLEADING_FACE: I SWEAR, THIS CODE REALLY DOES BELONG TO ME,
I AM NOT IMPERSONATING HIM. AND BY HIM, I MEAN ME OF COURSE. IVE GIVEN A LOT OF PERSONAL
DETAILS SO YOU ARE CONVINCED, R-RIGHT? HAVE A NICE CODE GUESSING
